#pragma once

#ifndef __GTL__wx__
#define __GTL__wx__

/**
@file
Subclass of xMatView, which is generated by wxFormBuilder.
*/

#include "_lib_gtl_wx.h"

#pragma comment (lib, "wx.lib")

#endif // __GTL__wx__
