#pragma once

#define GTL_STRING_PRIMITIVES__WINDOWS_FRIENDLY false
#define GTL_STRING_PRIMITIVES__USE_STD true
#define GTL_STRING_SUPPORT_CODEPAGE_KSSM true

#define GTL_DEFAULT_CODEPAGE 949	// for Windows only.
