#ifndef __IDlgMatViewOption__
#define __IDlgMatViewOption__

/**
@file
Subclass of IDlgMatViewOption, which is generated by wxFormBuilder.
*/

#include "gtl/wx/_lib_gtl_wx.h"
#include "gtl/wx/MatView.h"

//// end generated include

namespace gtl::wx {

	/** Implementing IDlgMatViewOption */
	class GTL__WX_CLASS xDlgMatViewOption : public ui::IDlgMatViewOption {
	public:
		using this_t = xDlgMatViewOption;
		using base_t = ui::IDlgMatViewOption;
	public:
		/** Constructor */
		xDlgMatViewOption(xMatView::S_OPTION const& option, wxWindow* parent);

		xMatView::S_OPTION m_option;

	protected:
		// Handlers for IDlgMatViewOption events.
		virtual void OnCheckBox_Skia( wxCommandEvent& event ) override;
		virtual void OnButtonClick_RestoreBackgroundColor(wxCommandEvent& event) override;
		virtual void OnButtonClick_OK( wxCommandEvent& event ) override;
		virtual void OnButtonClick_Cancel( wxCommandEvent& event ) override;

	//// end generated class members
	};


} // namespace gtl

#endif // __IDlgMatViewOption__
